# Generated by Django 5.0.6 on 2026-05-31 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Modelo del equipo', max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('MONO', 'Monocromático'), ('COLOR', 'Color')], default='MONO', max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'En mantenimiento')], default='ACTIVO', max_length=20)),
                ('cliente_id', models.PositiveIntegerField(blank=True, help_text='ID del cliente en ms-clientes', null=True)),
                ('contrato_id', models.PositiveIntegerField(blank=True, help_text='ID del contrato en ms-contratos', null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('cuota_mensual', models.PositiveIntegerField(default=5000, help_text='Ciclos de motor incluidos en el contrato por mes', validators=[django.core.validators.MinValueValidator(1)])),
                ('contador_inicial', models.PositiveIntegerField(default=0)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LecturaContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('contador', models.PositiveIntegerField(help_text='Valor del contador en ciclos de motor al momento de la lectura', validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True)),
                ('registrado_por', models.CharField(blank=True, max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Lectura de Contador',
                'verbose_name_plural': 'Lecturas de Contador',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('K', 'Negro'), ('C', 'Cian'), ('M', 'Magenta'), ('Y', 'Amarillo')], max_length=1)),
                ('capacidad_paginas', models.PositiveIntegerField(help_text='Páginas totales que rinde el tóner nuevo', validators=[django.core.validators.MinValueValidator(1)])),
                ('paginas_restantes', models.PositiveIntegerField(help_text='Páginas estimadas restantes en el tóner actual')),
                ('umbral_alerta_pct', models.PositiveSmallIntegerField(default=15, help_text='% restante al que se genera alerta', validators=[django.core.validators.MinValueValidator(1)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toners', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Tóner',
                'verbose_name_plural': 'Tóneres',
                'ordering': ['canal'],
            },
        ),
        migrations.CreateModel(
            name='CambioToner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('paginas_al_cambio', models.PositiveIntegerField(help_text='Páginas restantes cuando se hizo el cambio (para estadísticas)')),
                ('notas', models.TextField(blank=True)),
                ('realizado_por', models.CharField(blank=True, max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('toner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='equipos.toner')),
            ],
            options={
                'verbose_name': 'Cambio de Tóner',
                'verbose_name_plural': 'Cambios de Tóner',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='lecturacontador',
            constraint=models.UniqueConstraint(fields=('equipo', 'fecha'), name='unique_lectura_equipo_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='toner',
            unique_together={('equipo', 'canal')},
        ),
    ]
